config/routes.rb
Photogur::Application.routes.draw do

  root :to => "pictures#index"

  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	attr_accessible :title, 
		:artist, 
		:url, 
		:thumbnail_url,
		:copyrighted

	validates :title, :presence => true
	validates :url, 
		:presence => true,
		:format => { 
			:with => /^https?:\/\/[^\s]+$/i,
			:message => "Please enter a valid URL." 
		}

	validates :thumbnail_url, 
		:presence => true,
		:format => { 
			:with => /^https?:\/\/[^\s]+$/i,
			:message => "Please enter a valid URL." 
		}

	scope :alphabetical, order("title ASC")
	scope :free, where(:copyrighted => false)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    if params[:only_free]
      @pictures = Picture.free.alphabetical
    else
      @pictures = Picture.alphabetical
    end
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      flash[:notice] = "Picture was created."
      redirect_to pictures_path
    else
      # There was an error on the form.
      flash.now[:error] = "Please fix the errors below."
      render :new
    end

  end

  def show
    id = params[:id]
    @picture = Picture.find(id)
  end

  def edit
    id = params[:id]
    @picture = Picture.find(id)
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(params[:picture])
      flash[:notice] = "Picture was updated."
      redirect_to @picture
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      flash[:notice] = "Picture was deleted."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to 'Photogur', root_path %></h1>
<% if flash[:error] %>
	<section id="flash" class="error"><%= flash[:error] %></section>
<% elsif flash[:notice] %>
	<section id="flash" class="notice"><%= flash[:notice] %></section>
<% end %>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
	<p>
		<%= f.text_field "artist", 
			:placeholder => "Artist",
			:title => "Artist" %>
	</p>
	<p>
		<div class="error"><%= @picture.errors[:title].join(", ").capitalize %></div>
		<%= f.text_field "title", 
			:placeholder => "Title",
			:title => "Title" %>
	</p>
	<p>
		<div class="error"><%= @picture.errors[:url].join(", ").capitalize %></div>
		<%= f.text_field "url",
			:placeholder => "URL",
			:title => "URL" %>
	</p>
	<p>
		<div class="error"><%= @picture.errors[:thumbnail_url].join(", ").capitalize %></div>
		<%= f.text_field "thumbnail_url",
			:placeholder => "Thumbnail URL",
		 	:title => "Thumbnail URL"
		%>
	</p>
	<p>
		<%= f.check_box "copyrighted" %>
		<%= f.label "copyrighted", "Copyrighted?" %>
	</p>
	<p>
		<%= f.submit "Add" %>	
	</p>
<% end %>

app/views/pictures/edit.html.erb
<nav id="left">
	<%= link_to '←', pictures_path, :title => "Back" %>
	<%= link_to '✘', @picture, 
			:method => :delete,
			:confirm => "Are you sure you want to delete this picture?",
			:title => "Delete this picture",
			:class => "delete"
	%>
</nav>

<%= render :partial => "form" %>

<img src="<%= @picture.url %>" id="fullscreen">

app/views/pictures/index.html.erb
<nav id="left">
	<%= link_to '+', new_picture_path, 
		:title => "Add picture",
		:class => "new" %>
</nav>
<h2>Some interesting pictures.</h2>
<div class="index">
	<% @pictures.each do |pic| %>
		<%= link_to(pic) do %>
			<article>
				<%= image_tag pic.thumbnail_url %>
				<caption>
					<strong><%= pic.title %></strong> 
					by 
					<em><%= pic.artist %></em>
				</caption>
				<% if pic.copyrighted %>
					<span class="copy">&copy;</span>
				<% end %>
			</article>
		<% end %>
	<% end %>
</div>

app/views/pictures/new.html.erb
<nav id="left">
	<%= link_to '←', pictures_path, :title => "Back" %>
</nav>
<h2>Add a picture</h2>

<%= render :partial => "form" %>

app/views/pictures/show.html.erb
<h3>
	<%= @picture.title %> 
	<em>(<%= @picture.copyrighted ? "&copy;".html_safe : "" %>
		<%= @picture.artist %> )</em>
</h3>
<nav id="left">
	<%= link_to "←", pictures_path, :title => "Back" %>
	<%= link_to "✏", edit_picture_path(@picture.id), :title => "Edit this picture" %>
</nav>
<div class="show">
	<%= image_tag @picture.url, :id => "fullscreen" %>
</div>